## Testing logic:

In [17]:
import pandas as pd
import requests
import json
import datetime
import time
import numpy as np
import os



# https://stackoverflow.com/questions/78757696/

In [10]:
# BDay is business day, not birthday...
from pandas.tseries.offsets import BDay

today = datetime.datetime.today()
ten_biz_days_before = today - BDay(10)

from_date = ten_biz_days_before.strftime("%d-%m-%Y")
to_date = today.strftime("%d-%m-%Y")

print(from_date)
print(to_date)

03-07-2024
17-07-2024

In [11]:
df = pd.read_csv("stocklist.csv")
stock_list = df["SYMBOL"].tolist()
df.head(3)

   SYMBOL
0  LXCHEM
1    LTIM
2     M&M

In [12]:
# List of URLs
url1 = "https://www.nseindia.com/report-detail/eq_security"
url2 = "https://www.nseindia.com/api/historical/securityArchives?from=06-07-2024&to=17-07-2024&symbol=DMART&dataType=deliverable&series=EQ"


# Header
header1 = {
    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
}

s = requests.Session()
s.headers.update(header1)
r1 = s.get(url1)
s.headers.update(header1)

stock_name = "AFFLE"

url2 = "https://www.nseindia.com/api/historical/securityArchives?from="+from_date+"&to="+to_date+"&symbol="+stock_name+"&dataType=deliverable&series=EQ"
r2 = s.get(url2, cookies=r1.cookies)

#print(r2.text)

df2 = pd.DataFrame([])
if r2.status_code == 200:
    delivery_data = json.loads(r2.text)
    delivery_data = delivery_data.get('data')
    df2 = pd.DataFrame.from_dict(delivery_data, orient='columns')
    df2.drop(['_id', 'COP_SR_NOS', 'COP_TRADED_QTY','TIMESTAMP','COP_DELIV_QTY','createdAt','updatedAt', 'mTIMESTAMP', '__v'], axis=1, inplace=True)

df2

  COP_SYMBOL COP_SERIES  COP_DELIV_PERC COP_TRADED_DT
0      AFFLE         EQ           55.10    2024-07-03
1      AFFLE         EQ           35.92    2024-07-04
2      AFFLE         EQ           43.01    2024-07-05
3      AFFLE         EQ           36.93    2024-07-08
4      AFFLE         EQ           26.37    2024-07-09
5      AFFLE         EQ           38.92    2024-07-10
6      AFFLE         EQ           41.35    2024-07-11
7      AFFLE         EQ           38.85    2024-07-12
8      AFFLE         EQ           45.17    2024-07-15
9      AFFLE         EQ           55.83    2024-07-16

In [25]:
df2['COP_DELIV_PERC'].to_list()

[55.1, 35.92, 43.01, 36.93, 26.37, 38.92, 41.35, 38.85, 45.17, 55.83]

## For loop:

In [1]:
import pandas as pd
import requests
import json
import datetime
import time
import numpy as np

In [2]:
# BDay is business day, not birthday...
from pandas.tseries.offsets import BDay

today = datetime.datetime.today()
ten_biz_days_before = today - BDay(10)

from_date = ten_biz_days_before.strftime("%d-%m-%Y")
to_date = today.strftime("%d-%m-%Y")

print(from_date)
print(to_date)

03-07-2024
17-07-2024

In [3]:
df = pd.read_csv("stocklist.csv")
stock_list = df["SYMBOL"].tolist()
df.head(5)

    SYMBOL
0   LXCHEM
1     LTIM
2      M&M
3  MANKIND
4   MARICO

In [4]:
stock_list

['LXCHEM',
 'LTIM',
 'M&M',
 'MANKIND',
 'MARICO',
 'MARUTI',
 'MAZDOCK',
 'METROBRAND',
 'MTARTECH',
 'MUTHOOTFIN',
 'NAVINFLUOR',
 'NAZARA',
 'NEOGEN',
 'NESTLEIND',
 'NETWEB',
 'PAGEIND',
 'PARAS',
 'PERSISTENT',
 'PIIND',
 'PIDILITIND',
 'POLYCAB',
 'PRINCEPIPE',
 'RVNL',
 'RAILTEL',
 'RAYMOND',
 'RELAXO',
 'RELIANCE',
 'ROSSARI',
 'ROUTE',
 'SBIN',
 'SIEMENS',
 'SONACOMS',
 'SRF',
 'SUNPHARMA',
 'TCS',
 'TATACONSUM',
 'TATAELXSI',
 'TATAMOTORS',
 'TATAPOWER',
 'TATATECH',
 'TITAN',
 'TRENT',
 'TIINDIA',
 'TVSMOTOR',
 'UBL',
 'UNITDSPR',
 'UNOMINDA',
 'VBL',
 'VINATIORGA',
 'VOLTAS',
 'WESTLIFE',
 'WIPRO',
 'YASHO',
 'ZENTEC',
 'AARTIDRUGS',
 'AARTIIND',
 'AARTIPHARM',
 'AARTISURF',
 'ABB',
 'ACC',
 'AFFLE',
 'ALKYLAMINE',
 'ANGELONE',
 'ASAHIINDIA',
 'ASHOKLEY',
 'ASIANPAINT',
 'ASTRAL',
 'DMART',
 'AXISBANK',
 'BAJAJ-AUTO',
 'BAJAJELEC',
 'BAJFINANCE',
 'BAJAJFINSV',
 'BALAMINES',
 'BATAINDIA',
 'BERGEPAINT',
 'BEL',
 'BHARTIARTL',
 'BOROLTD',
 'BRITANNIA',
 'BSE',
 'CAMPUS',
 'CDSL',
 'CENTUM',
 'CGPOWER',
 'COCHINSHIP',
 'COFORGE',
 'CAMS',
 'CONCOR',
 'MUFTI',
 'CYIENT',
 'DABUR',
 'DEEPAKNTR',
 'DIVISLAB',
 'DIXON',
 'DRREDDY',
 'LALPATHLAB',
 'EICHERMOT',
 'ETHOSLTD',
 'EXIDEIND',
 'FINEORG',
 'GRSE',
 'GMMPFAUDLR',
 'GODREJPROP',
 'GREENLAM',
 'GREENPANEL',
 'HAPPSTMNDS',
 'HAVELLS',
 'HCL',
 'HDFCAMC',
 'HDFCBANK',
 'HDFCLIFE',
 'HERITGFOOD',
 'HEROMOTOCO',
 'HAL',
 'HNDFDS',
 'HINDUNILVR',
 'HLEGLAS',
 'ICICIBANK',
 'ICICIGI',
 'ICICIPRULI',
 'IDEAFORGE',
 'IDFCFIRSTB',
 'IRCTC',
 'IREDA',
 'NAUKRI',
 'INFY',
 'INDIGO',
 'IRCON',
 'ITC',
 'JIOFIN',
 'JUBLFOOD',
 'KALYANKJIL',
 'KAYNES',
 'KEI',
 'KOTAKBANK',
 'KPIGREEN',
 'KPITTECH',
 'LTTS',
 'LT']

In [9]:
def test_abnormal(list_data):
    q75, q25 = np.percentile(list_data[:-1], [75 ,25])
    iqr = q75 - q25
    threshold = q75 + 1.75 * iqr
    last_value = list_data[-1]
    abnormal = False
    if last_value > threshold:
        abnormal = True
    else: 
        abnormal = False

    return abnormal

In [10]:
# List of URLs
url1 = "https://www.nseindia.com/report-detail/eq_security"

# Header
header1 = {
    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
}


s = requests.Session()
s.headers.update(header1)
r1 = s.get(url1)
s.headers.update(header1)


result = []
df3 = pd.DataFrame([])

for stock in stock_list: 
    print("Processing stock: ",stock)
    stock_name = stock
    url2 = "https://www.nseindia.com/api/historical/securityArchives?from="+from_date+"&to="+to_date+"&symbol="+stock_name+"&dataType=deliverable&series=EQ"
    r2 = s.get(url2, cookies=r1.cookies)
    time.sleep(1)
    if r2.status_code == 200:
        delivery_data = json.loads(r2.text)
        delivery_data = delivery_data.get('data') 
        if len(delivery_data)==0:
            result.append({'Stock Symbol': stock_name, 'Delivery to Trade Percentage' : '-1', 'Date' : 'Err', 'High Delivery' : 'Err' }) 
        else: 
            #print(delivery_data)
            df2 = pd.DataFrame.from_dict(delivery_data, orient='columns')
            df2.drop(['_id', 'COP_SR_NOS', 'COP_TRADED_QTY','TIMESTAMP','COP_DELIV_QTY','createdAt','updatedAt', 'mTIMESTAMP', '__v'], axis=1, inplace=True)
            report_date = df2["COP_TRADED_DT"].tolist()[-1]  # Last element in list 
            delivery_pct = df2["COP_DELIV_PERC"].tolist()[-1]  # Last element in list

            delivery_pct_list = df2["COP_DELIV_PERC"].tolist() 

            if test_abnormal(delivery_pct_list) : 
                result.append({'Stock Symbol': stock_name, 'Delivery to Trade Percentage' : delivery_pct, 'Date' : report_date, 'High Delivery' : 'Yes' })
            else: 
                result.append({'Stock Symbol': stock_name, 'Delivery to Trade Percentage' : delivery_pct, 'Date' : report_date, 'High Delivery' : 'No' })
  
    else:
        result.append({'Stock Symbol': stock_name, 'Delivery to Trade Percentage' : '-1', 'Date' : 'Err', 'High Delivery' : 'Err' })

    
df3 = pd.DataFrame.from_dict(result, orient='columns')

Processing stock:  LXCHEM
Processing stock:  LTIM
Processing stock:  M&M
Processing stock:  MANKIND
Processing stock:  MARICO
Processing stock:  MARUTI
Processing stock:  MAZDOCK
Processing stock:  METROBRAND
Processing stock:  MTARTECH
Processing stock:  MUTHOOTFIN
Processing stock:  NAVINFLUOR
Processing stock:  NAZARA
Processing stock:  NEOGEN
Processing stock:  NESTLEIND
Processing stock:  NETWEB
Processing stock:  PAGEIND
Processing stock:  PARAS
Processing stock:  PERSISTENT
Processing stock:  PIIND
Processing stock:  PIDILITIND
Processing stock:  POLYCAB
Processing stock:  PRINCEPIPE
Processing stock:  RVNL
Processing stock:  RAILTEL
Processing stock:  RAYMOND
Processing stock:  RELAXO
Processing stock:  RELIANCE
Processing stock:  ROSSARI
Processing stock:  ROUTE
Processing stock:  SBIN
Processing stock:  SIEMENS
Processing stock:  SONACOMS
Processing stock:  SRF
Processing stock:  SUNPHARMA
Processing stock:  TCS
Processing stock:  TATACONSUM
Processing stock:  TATAELXSI
Processing stock:  TATAMOTORS
Processing stock:  TATAPOWER
Processing stock:  TATATECH
Processing stock:  TITAN
Processing stock:  TRENT
Processing stock:  TIINDIA
Processing stock:  TVSMOTOR
Processing stock:  UBL
Processing stock:  UNITDSPR
Processing stock:  UNOMINDA
Processing stock:  VBL
Processing stock:  VINATIORGA
Processing stock:  VOLTAS
Processing stock:  WESTLIFE
Processing stock:  WIPRO
Processing stock:  YASHO
Processing stock:  ZENTEC
Processing stock:  AARTIDRUGS
Processing stock:  AARTIIND
Processing stock:  AARTIPHARM
Processing stock:  AARTISURF
Processing stock:  ABB
Processing stock:  ACC
Processing stock:  AFFLE
Processing stock:  ALKYLAMINE
Processing stock:  ANGELONE
Processing stock:  ASAHIINDIA
Processing stock:  ASHOKLEY
Processing stock:  ASIANPAINT
Processing stock:  ASTRAL
Processing stock:  DMART
Processing stock:  AXISBANK
Processing stock:  BAJAJ-AUTO
Processing stock:  BAJAJELEC
Processing stock:  BAJFINANCE
Processing stock:  BAJAJFINSV
Processing stock:  BALAMINES
Processing stock:  BATAINDIA
Processing stock:  BERGEPAINT
Processing stock:  BEL
Processing stock:  BHARTIARTL
Processing stock:  BOROLTD
Processing stock:  BRITANNIA
Processing stock:  BSE
Processing stock:  CAMPUS
Processing stock:  CDSL
Processing stock:  CENTUM
Processing stock:  CGPOWER
Processing stock:  COCHINSHIP
Processing stock:  COFORGE
Processing stock:  CAMS
Processing stock:  CONCOR
Processing stock:  MUFTI
Processing stock:  CYIENT
Processing stock:  DABUR
Processing stock:  DEEPAKNTR
Processing stock:  DIVISLAB
Processing stock:  DIXON
Processing stock:  DRREDDY
Processing stock:  LALPATHLAB
Processing stock:  EICHERMOT
Processing stock:  ETHOSLTD
Processing stock:  EXIDEIND
Processing stock:  FINEORG
Processing stock:  GRSE
Processing stock:  GMMPFAUDLR
Processing stock:  GODREJPROP
Processing stock:  GREENLAM
Processing stock:  GREENPANEL
Processing stock:  HAPPSTMNDS
Processing stock:  HAVELLS
Processing stock:  HCL
Processing stock:  HDFCAMC
Processing stock:  HDFCBANK
Processing stock:  HDFCLIFE
Processing stock:  HERITGFOOD
Processing stock:  HEROMOTOCO
Processing stock:  HAL
Processing stock:  HNDFDS
Processing stock:  HINDUNILVR
Processing stock:  HLEGLAS
Processing stock:  ICICIBANK
Processing stock:  ICICIGI
Processing stock:  ICICIPRULI
Processing stock:  IDEAFORGE
Processing stock:  IDFCFIRSTB
Processing stock:  IRCTC
Processing stock:  IREDA
Processing stock:  NAUKRI
Processing stock:  INFY
Processing stock:  INDIGO
Processing stock:  IRCON
Processing stock:  ITC
Processing stock:  JIOFIN
Processing stock:  JUBLFOOD
Processing stock:  KALYANKJIL
Processing stock:  KAYNES
Processing stock:  KEI
Processing stock:  KOTAKBANK
Processing stock:  KPIGREEN
Processing stock:  KPITTECH
Processing stock:  LTTS
Processing stock:  LT

In [11]:
df3

    Stock Symbol Delivery to Trade Percentage        Date High Delivery
0         LXCHEM                        42.23  2024-07-16            No
1           LTIM                        30.59  2024-07-16            No
2            M&M                           -1         Err           Err
3        MANKIND                        71.56  2024-07-16            No
4         MARICO                         44.2  2024-07-16            No
..           ...                          ...         ...           ...
135    KOTAKBANK                        71.69  2024-07-16            No
136     KPIGREEN                        45.82  2024-07-16            No
137     KPITTECH                        33.43  2024-07-16            No
138         LTTS                        34.62  2024-07-16            No
139           LT                        69.73  2024-07-16            No

[140 rows x 4 columns]

In [12]:
df3.to_csv('Report.csv', index=False)

In [13]:
import numpy as np 

def test_abnormal(list_data):
    q75, q25 = np.percentile(list_data[:-1], [75 ,25])
    iqr = q75 - q25
    threshold = q75 + 2 * iqr
    last_value = list_data[-1]
    abnormal = False
    print("IQR is : ",str(iqr))
    print("Threshold is : ",str(threshold))
    if last_value > threshold:
        abnormal = True

    return abnormal

my_pct = [59.45, 55.2, 54.16, 66.57, 68.62, 64.19, 60.57, 44.12, 71.52, 90.2]
my_pct = [55.1, 35.92, 43.01, 36.93, 26.37, 38.92, 41.35, 38.85, 45.17, 55.83]
test_abnormal(my_pct)

IQR is :  6.079999999999998
Threshold is :  55.169999999999995

True